### ISSUE TITLE
Moji utisci 

### ISSUE THREAD

**Issue by NiKola-UE** [RHVoice/suze-mkd#1]
Zdravo, Branislave @Gerazov i svi ostali. 

Najpre, mislim da vam ne smeta što pišem na srpskom jer makedonski ne znam baš najbolje, a ne moram na engleskom s obzirom na to da se dobro razumemo. 

Kao što naslov kaže, izneo bih ovde svoje utiske. Glas je odlično urađen i tehnički je kvalitetniji od srpske Dragane koja je rađena eksperimentalno, u znatno skromnijim uslovima i sa malim timom učesnika. Kao i Kiko, tako i Suze odlično čita srpske i hrvatske tekstove, s tim što ne može prepoznati srpska ćirilička slova Ђ i Ћ koja su malo drukčija od makedonskih "ekvivalenata", kao što ni Dragana ne prepoznaje makedonska slova Ѓ i Ќ iako ona postoje na srpskoj ćiriličkoj tastaturi. Ne dopada mi se to što slova pri pisanju i čitanju izgovara, odnosno  speluje kao da su engleska, pa tada to teže razumem, a mnogo engleskih reči izgovara kao Vokalizatorova Lana ("Čange", "Speeh" itd); mada su strani jezici generalno zajednički problem za većinu RHVoiceovih glasova. Naravno, treba sređivati, popravljati i dopunjavati  rečnike i za to treba mnogo vremena. Ja sam spreman pomoći i rado ću to učiniti koliko god mogu, ali ne znam kako, tj ne poznajem programske jezike niti koji se parametri koriste. I sam bi trebalo da se uključim u razvoj RHVoicea s iskrenom željom da doprinesem njegovom poboljšanju, ali sam sprečen. Takođe, nadam se da će unapređena Suze biti dostupna i na Androidu. 

Hvala

**Comment by gerazov** [comment]
Хеј шефе - јел можеш овај коментар послати на мој мејл, лакше је да тамо продискутирамо [gerazov@feit.ukim.edu.mk](mailto:gerazov@feit.ukim.edu.mk)

**Comment by zstanecic** [comment]
Zdravo Branislave i Nikola,
Mislim da se ovdje nema što diskutirati.
Ne treba miješati babe i žabe. jedno je glas, a drugo je jezik. Budući da ovo nije tema diskusije, predlažem da ovaj issue zatvorimo.
Put do pakla je popločan dobrim namjeama, kaže naša stara poslovica.
Postoji razlog zašto se change izgovara kao čange. 
Naime, trebao bi poznavati kontekst makedonske grafije za latinicu i transliteracije makedonskog kako bi mogao tvrditi kako je nešto pogrešno ili ne.
Dakle: u internet prostoru makedonojezičnom, postoje dva načina zapisivanja / transliteriranja mekedonskih dijakritičkih znakova, kada oni nisu dostupni na ćirilici, ili korisnik ne želi prebacivati tastature: digrafni i monografni sistem.
Digrafni sistem koristi ch, zh, dj, i kj kao kombinacije za transliteraciju makedonskih slova u latinicu, dok monografni koristi srpske / hrvatske dijakritičke znakove latinice.
@bgerazov 
slažeš li se?

**Comment by NiKola-UE** [comment]
Pozdrav, Zvonimire. 




Samo sam hteo podeliti svoja iskustva kao korisnik i nije mi jasno šta je tu problem. Ti si jezikoslovac i programer, ja nisam, pa ne mogu ulaziti dublje u ovo što si rekao. Kad nešto ne znaš, verovatno ćeš negde pogrešiti. Ovo za izgovor engleskih reči sam naveo zato što kod Kika to ne primećujem ili je bar toga manje, bez obzira na to što je taj glas, samim tim i projekat rađen potpuno nezavisno. Ipak, ne mislim da je u skladu s makedonskim da se latinička slova izgovaraju kao "Ej", "Bi", "Si", "Di" itd, što kod Kika takođe nije slučaj. Čak ni Ispik ova slova na makedonskom ne izgovara tako. Da ne spominjem prve verzije Anridera koje su podržavale makedonski, ali su to zapravo bili samo prerađeni srpski glasovi, iako se gramatika ovih jezika znatno razlikuje (isto je učinjeno i u češkom Vintokeru kada su češki i slovački glasovi postali srpski, a Majkrosoft je za Azur čak od gruzijskih glasova napravio hrvatske). Znam, to nije tema, ali treba sagledavati širu sliku. Poenta je da se poboljša prepoznavanje i razumevanje stranih jezika, a mnogo toga se zasigurno može popraviti dopunjavanjem rečnika. Rekoh i to da sam spreman pomoći oko njihovog sređivanja, a ti na SliKomu lepo napisa da su naši jezici prilično nepredvidljivi. A da Suze bude dostupna za Android bi bilo dobro, zar ne? 



Poređenje s Draganom je neminovno jer su to srodni jezici i naravno RHVoice glasovi koji dele mnogo toga zajedničkog, bez obzira na to kako su sintetizovani. 



Neću ovde o tome, ali ako si ljut što ti nisam poslao obećane snimke, to je jednostavno zato što je samo snimanje preskupo; mnogo više nego što sam mislio i moja je greška što sam istrčao pred rudu. Moraću pisati projekat za koji je pitanje hoće li uopšte proći, ali o svemu ćeš biti blagovremeno obavešten. Zašto bih prevario nekog s kim želim sarađivati? 



Što se tiče izreke (kad već pričamo o tome), više mi se sviđa ona: "U raju je možda lepo, ali je u paklu ekipa." 




Branislave, mogu proslediti komentar putem e-pošte, ali nisam siguran hoće li stići jer Autluk neretko otkazuje poslušnost, a e-adresu ne mogu odmah i tek tako promeniti. Moj mejl je 
ni-kola.ue@outlook.com. Napominjem da sam ja još uvek samo običan korisnik koji ne zna kako se izrađuju govorne sinteze, pa ne treba da čudi ako sam napisao nešto netačno.

**Comment by NiKola-UE** [comment]
@gerazov: 
Poslao sam ti imejl, ali nisam siguran je li stigao. Ako nije, mogu poslati opet, mada sam sve već rekao ovde. 











@zstanecic: 
Razumej da ja nemam toliko znanja kao ti i zato pišem ono što je tebi možda besmisleno. Nema razloga da se zbog toga živciraš i reaguješ burno jer mi nikako nije namera da nekog kudim ili omalovažavam nečiji rad. Izvinjavam se ako sam ostavio takav utisak, ali sam samo hteo da se informišem i nekako pomognem u daljem razvoju koliko je moguće. 






Da ne ispadne kako dižem tenzije, postaviću nekoliko pitanja (nije važno ko će odgovoriti, samo neka bude bilo kakvog odgovora). Evo, obećavam da ću zatvoriti ovu temu nakon što nešto od ovoga saznam. 




Ono najvažnije: Nepalski, sesvanski, vijetnamski i španski glasovi su se pojavili pre nekoliko meseci, a slovačka Jasietka pre manje od mesec dana i svi su već dostupni za Android, a Suze nije. Branko mi je putem mejla objasnio zašto i sad ću reći samo toliko da je tako nešto poslednje što bi se očekivalo od jednog slobodnog i otvorenog softvera koji bi trebalo da to zaista i jeste. 








Mogu li se monografski i digrafski sistemi kombinovati i da li se ponekad koristi i bugarska ćirilica? 

















Koji su razlozi što Suze latinička slova speluje kao engleska i zašto Đ izgovara kao Dj, što kod Kika nije slučaj? 

















Rekao sam i to da je snalaženje sa stranim jezicima globalni problem RHVoicea i o tome smo već razgovarali. U redu, za specifičan izgovor postoje opravdani razlozi. Ali od čega će zavisiti koliko će neki glas (u ovom slučaju Suze) strane, najčešće engleske reči izgovarati više ili manje tačno? Tako, ruski, ukrajinski i čak neki centralnoazijski glasovi (a mnoge od njih si ti trenirao) dobar deo engleskih reči izgovaraju prilično tačno, što je zanimljivo jer si i ruska i ukrajinska tastatura / tipkovnica prilično i po mnogo čemu razlikuju od ovih naših, dok centralnoazijski jezici uopšte nisu indoevropski, bez obzira na to koja se pisma koriste. 





















I na kraju, kako se to može ispraviti, odnosno mogu li se bar najpoznatije reči fonetski zapisivati onako kako se izgovaraju po Adelungovom pravilu, opet bez obzira na to koje se pismo koristi? 

















Sve ovo pitam i zbog toga što: 


> "Rječnik naglasaka moramo popunjavati ručno i ispravljati probleme sa svim mogućim riječima. Na žalost, takva je sudbina naših jezika, koji imaju nepredvidljiva pravila naglašavanja. Ovo je prva stabilna verzija, a updateova će biti, i tu nećemo stati samo na jednoj verziji, jer kao što si rekao, prostora za poboljšanje ima, ali te riječi treba i popisati." 






Da, upravo na ovo mislim i želim da sarađujemo. Ovaj tvoj komentar se ne odnosi na Suze, ali je kontekst ipak isti i zato mislim da i na ovome treba raditi, u čemu ću ja takođe učestvovati ako se slažeš. 









Naravno, možeš mi odgovoriti i putem e-pošte ako tako želiš, samo bez frustracija i nervoze jer zaista nisam mislio ništa loše. Nisam nikakav kritizer, nego običan korisnik koji voli eksperimentisati i neizmenično koristiti više različitih glasova (što je samo još jedna od prednosti RHVoicea koju malo koji slični softver ima, a što je na Androidu mnogo lakše i izvodljivije) i početnik u razumevanju rada govornih sintetizatora, kako već napomenuh, što si i ti nekad bio. 





























Srdačan pozdrav i hvala na edukaciji

**Comment by NiKola-UE** [comment]
Najbolje je da od sada o ovakvim stvarima razgovaramo putem e-pošte jer je tako praktičnije. U buduće ćemo činiti tako.
